name: Deploy to Azure App Service

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords wordnet

      - name: Prepare deployment files
        run: |
          # Créer des fichiers __init__.py dans tous les dossiers pour les packages Python
          find . -type d -not -path "*/\.*" -not -path "*/venv*" -exec touch {}/__init__.py \;

          # Supprimer wsgi.py si présent
          rm -f wsgi.py

          # Supprimer startup.txt si présent
          rm -f startup.txt

          # S'assurer que startup.sh est exécutable
          chmod +x startup.sh

          # Vérifier la structure finale
          find . -type f -name "*.py" | sort

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'trabsa-dashboard'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
