name: Deploy to Azure App Service

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Optimisation: mise en cache des dépendances pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords wordnet

      - name: Prepare deployment files
        run: |
          # Créer des fichiers __init__.py dans tous les dossiers pour les packages Python
          find . -type d -not -path "*/\.*" -not -path "*/venv*" -exec touch {}/__init__.py \;

          # Vérifier que startup.txt existe et a le bon contenu
          if [ ! -f "startup.txt" ]; then
            echo "gunicorn --bind=0.0.0.0 --timeout 600 --workers 2 --threads 2 wsgi:app" > startup.txt
          fi

          # Vérifier la présence de wsgi.py
          if [ ! -f "wsgi.py" ]; then
            echo "ERREUR: fichier wsgi.py manquant!"
            exit 1
          fi

      - name: Validate deployment configuration
        run: |
          echo "Configuration de déploiement:"
          echo "- Python: $(python --version)"
          echo "- Contenu de startup.txt: $(cat startup.txt)"
          echo "- Structure de fichiers:"
          find . -type f -name "*.py" | sort

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'trabsa-dashboard'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          startup-command: '' # Champ vide pour s'assurer que startup.txt est utilisé
